In [33]:
import pandas as pd
import sys,os
import datetime as dt
import subprocess as sp
import glob

In [15]:
jhu_daily_root='https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/'
outdir='/s/data/covid19/daily'
os.makedirs(outdir,exist_ok=True)
sdate=dt.datetime(2020,3,22).date()
edate=dt.datetime.now().date()

In [46]:
for i in pd.date_range(sdate,edate):
    fname=i.date().strftime('%m-%d-%Y')+'.csv'
    rname = jhu_daily_root+fname
    lname = os.path.join(outdir,fname)
    cmd='wget -c -O {} {}\n'.format(lname,rname)
    sp.call(cmd.split())
daily=[x for x in glob.glob(os.path.join(outdir,'*.csv')) if os.stat(x).st_size>0]
daily.sort()

In [52]:
df = pd.read_csv(daily[0])
for i in daily[1:]:
    df = df.append(pd.read_csv(i))
df.dropna(inplace=True)

In [55]:
df

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-03-31 23:43:56,34.223334,-82.461707,4,0,0,0,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-03-31 23:43:56,30.295065,-92.414197,39,1,0,0,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-03-31 23:43:56,37.767072,-75.632346,7,0,0,0,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-03-31 23:43:56,43.452658,-116.241552,195,3,0,0,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-03-31 23:43:56,41.330756,-94.471059,1,0,0,0,"Adair, Iowa, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
2167,51199.0,York,Virginia,US,2020-03-31 23:43:56,37.243748,-76.544128,14,1,0,0,"York, Virginia, US"
2168,48503.0,Young,Texas,US,2020-03-31 23:43:56,33.176597,-98.687909,1,0,0,0,"Young, Texas, US"
2169,6115.0,Yuba,California,US,2020-03-31 23:43:56,39.262559,-121.353564,6,0,0,0,"Yuba, California, US"
2170,4027.0,Yuma,Arizona,US,2020-03-31 23:43:56,32.768957,-113.906667,9,0,0,0,"Yuma, Arizona, US"
2171,8125.0,Yuma,Colorado,US,2020-03-31 23:43:56,40.003468,-102.425867,2,0,0,0,"Yuma, Colorado, US"

In [62]:
dates = df.Last_Update.str.split(' ').apply(lambda x: dt.datetime.strptime(x[0].strip(),'%Y-%m-%d'))
df['Last_Update']=dates

In [71]:
df2=df.groupby(['Combined_Key','Last_Update']).sum()

In [76]:
confirmed=df2['Confirmed']

In [83]:
confirmed=confirmed.unstack()

In [86]:
confirmed.index[0]

'Abbeville, South Carolina, US'

In [100]:
df3  = pd.DataFrame(pd.Series(df[df.Combined_Key==confirmed.index[0]].iloc[0,:7]).append(confirmed.loc[confirmed.index[0]]))

In [103]:
series=[]
for i in confirmed.index:
    series.append(pd.DataFrame(pd.Series(df[df.Combined_Key==i].iloc[0,:7]).append(confirmed.loc[i])))

In [110]:
df4=pd.concat(series,axis=1)

In [120]:
df5=df4.T
df5

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,2020-03-23 00:00:00,2020-03-24 00:00:00,2020-03-25 00:00:00,2020-03-26 00:00:00,2020-03-27 00:00:00,2020-03-28 00:00:00,2020-03-29 00:00:00,2020-03-30 00:00:00,2020-03-31 00:00:00
0,45001,Abbeville,South Carolina,US,2020-03-31,34.2233,-82.4617,1,1,3,3,4,3,3,3,8
0,22001,Acadia,Louisiana,US,2020-03-31,30.2951,-92.4142,1,2,2,3,8,9,9,11,78
0,51001,Accomack,Virginia,US,2020-03-31,37.7671,-75.6323,1,1,2,2,2,2,3,6,14
0,16001,Ada,Idaho,US,2020-03-31,43.4527,-116.242,13,19,24,39,54,76,92,113,390
0,19001,Adair,Iowa,US,2020-03-31,41.3308,-94.4711,1,1,1,1,1,1,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,4027,Yuma,Arizona,US,2020-03-31,32.769,-113.907,2,2,3,4,4,4,5,6,18
0,8125,Yuma,Colorado,US,2020-03-31,40.0035,-102.426,1,1,1,2,2,2,2,2,4
0,48505,Zapata,Texas,US,2020-03-23,27.0016,-99.1699,0,0,0,0,0,0,0,0,NaN
0,48507,Zavala,Texas,US,2020-03-23,28.8662,-99.7605,0,0,0,0,0,0,0,0,NaN
0,46137,Ziebach,South Dakota,US,2020-03-23,44.9788,-101.665,0,0,0,0,0,0,0,0,NaN

In [121]:
df5.drop('Last_Update',1)

,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,2020-03-23 00:00:00,2020-03-24 00:00:00,2020-03-25 00:00:00,2020-03-26 00:00:00,2020-03-27 00:00:00,2020-03-28 00:00:00,2020-03-29 00:00:00,2020-03-30 00:00:00,2020-03-31 00:00:00
0,45001,Abbeville,South Carolina,US,34.2233,-82.4617,1,1,3,3,4,3,3,3,8
0,22001,Acadia,Louisiana,US,30.2951,-92.4142,1,2,2,3,8,9,9,11,78
0,51001,Accomack,Virginia,US,37.7671,-75.6323,1,1,2,2,2,2,3,6,14
0,16001,Ada,Idaho,US,43.4527,-116.242,13,19,24,39,54,76,92,113,390
0,19001,Adair,Iowa,US,41.3308,-94.4711,1,1,1,1,1,1,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,4027,Yuma,Arizona,US,32.769,-113.907,2,2,3,4,4,4,5,6,18
0,8125,Yuma,Colorado,US,40.0035,-102.426,1,1,1,2,2,2,2,2,4
0,48505,Zapata,Texas,US,27.0016,-99.1699,0,0,0,0,0,0,0,0,NaN
0,48507,Zavala,Texas,US,28.8662,-99.7605,0,0,0,0,0,0,0,0,NaN
0,46137,Ziebach,South Dakota,US,44.9788,-101.665,0,0,0,0,0,0,0,0,NaN